### PR TITLE
Embed Pdbs

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by mhutch** [comment]
Any particular reason you needed the PDBs to be embedded?

**Comment by KirillOsenkov** [comment]
We keep running out of file handles in VSMac and if the pdb is embedded it’s one less file to open :) It is also more convenient to always have the pdb embedded, stack traces get line numbers, debugging is faster. On small assemblies such as this the 10-15% binary size increase is negligible.

**Comment by KirillOsenkov** [comment]
In general I nowadays default to embedding pdbs everywhere unless it’s VSWin (where you need legacy pdbs for symbol publishing to work). Haven’t regretted this so far.

**Comment by KirillOsenkov** [comment]
Rebased to latest.

**Pull request merged**
