### PR TITLE
Delete XmlEditorOptions.cs

### PR DESCRIPTION
**Pull request by KirillOsenkov**
XmlEditorOptions is a host-IDE specific type and was moved to VSMac.

Set LangVersion to latest so we don't have to bump it again.

Exclude runtime assets from Editor NuGet packages to avoid copying editor binaries to output.

Add a reference to System.ComponentModel.Composition to make builds happy.

### CODE REVIEW

**Comment by mhutch** [comment]
This is failing tests.

I would probably combine the `PackageReference` changes here into an atomic commit with the resultant test project `PackageReference` changes in #39?

FWIW I had left `XmlEditorOptions.cs`  and the other `<None>` files pending audit for unported functionality. I think the remaining thing in this file is `AutoInsertFragments` (auto-inserting `=""`)

Language version bump is fine but I'd probably do it in `Directory.Build.props` so all projects are consistent?

**Comment by KirillOsenkov** [comment]
OK, I've extracted out 
https://github.com/mhutch/MonoDevelop.Xml/pull/41
https://github.com/mhutch/MonoDevelop.Xml/pull/42

**Comment by KirillOsenkov** [comment]
Lol I created a bit of a confusion with all these PRs :) I understand why the tests fail here.

I suggest you merge the LangVersion PR first, then I can clean up the rest and resubmit.

**Comment by KirillOsenkov** [comment]
And yes, we can keep XmlEditorOptions.cs if you like.

What is the exact ="" insertion behavior? Maybe I could take a look into it. Does any existing editor have it so I could see how it is supposed to work?

**Comment by KirillOsenkov** [comment]
We do insert "" after you press = after an attribute. I think this is why I wanted to be able to detect that a buffer position is at the end of an attribute.

**Pull request closed without merging**
