### PR TITLE
Provide a TextMate classification tagger for all XML languages.

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
This should supersede https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/master/MonoDevelop.MSBuild.Editor/MSBuildTextMateTagger.cs which I want to delete as well.

My question to you @mhutch is what were the reasons to create MSBuild.json (https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/master/MonoDevelop.MSBuildEditor/Syntax/msbuild.json) beside just adding the file extensions for MSBuild? And the fact that it's in Json format as opposed to Plist? It looks cleaner, but are there functional differences that we will lose if we switch to the Xml.plist from TextMate?

**Comment by mhutch** [comment]
MSBuild.json is a custom schema that supports highlighting MSBuild expressions

**Comment by mhutch** [comment]
This should merge into https://github.com/mhutch/MonoDevelop.Xml/pull/7 and move to MonoDevelop.XmlEditor

**Comment by KirillOsenkov** [comment]
Ah, good point. We don't need the classifier on Windows.

**Comment by KirillOsenkov** [comment]
I'll fold this into the other PR.

**Pull request closed without merging**
