### PR TITLE
XML classifier

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Add a parser-based XML classifier and tests.

We need to think about maybe having it off by default because if this is hosted in VS, VS already has its own XML classifier, so not sure whether they will conflict.

VSMac uses this classifier already.

### CODE REVIEW

**Comment by mhutch** [comment]
This is probably fine on VSWin - the XML classifier isn't active in my MSBuild editor, for example - I [explicitly opted into the TextMate tagger](https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/main/MonoDevelop.MSBuild.Editor/MSBuildTextMateTagger.cs) to get highlighting.

I would like to figure out a way to make this opt-in/extensible for derived languages. I have no idea how it would interact with TextMate tagger that the MSBuild editor uses, for example, so at the very least I'd want to be able to disable it. Ideally I'd want to be able to extend it to add MSBuild expression highlighting.

**Comment by KirillOsenkov** [comment]
I added IXmlClassifierExtension, let me know what you think.

I imagine MSBuildEditor would provide one.

**Comment by KirillOsenkov** [comment]
@mhutch do you have an MSBuild-specific classifier anywhere so we could test the extension point? I could probably write something simple that classifies contents of some attribute values as a simple test scenario.

**Comment by mhutch** [comment]
I don't have an MSBuild classifier, I just use the TextMate format - see https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/main/MonoDevelop.MSBuildEditor/Syntax/msbuild.json

I think the best approach here is probably to _not_ bind to `[ContentType (XmlContentTypeNames.XmlCore)]` but instead bind to the more derived content types and make the classifier non-sealed so other XML-derived languages can subclass it when implementing a classifier?

**Comment by KirillOsenkov** [comment]
OK, I unsealed the XmlClassifier class and made some members virtual.

Changed the classifier provider to export for Xml, Xslt and Xsd instead of XmlCore.

If you want, we could remove the XmlClassifierProvider altogether and have the host export it to give full control to the host.

Another problem is that XmlClassificationTypes is an enum, so not extensible. We could change to string constants I guess? Or ints?

Feel free to take over this PR and push directly to it if you like.

**Comment by KirillOsenkov** [comment]
If we ever need an XML classifier in this repo we can always revive this.

**Pull request closed without merging**
