### PR TITLE
Add VSMac XML addin.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
This is an early preview of the VSMac XML addin based on the new editor.

Feedback welcome!

### CODE REVIEW

**Comment by mhutch** [comment]
This should move to MonoDevelop.XmlEditor

**Comment by mhutch** [comment]
Looking good! Probably want some basic functionality before merging tho

**Comment by KirillOsenkov** [comment]
You mean rename the `VSMac` folder to `MonoDevelop.XmlEditor`?

**Comment by mhutch** [comment]
Oops, I mixed up tabs. meant that comment for https://github.com/mhutch/MonoDevelop.Xml/pull/6/.

**Comment by KirillOsenkov** [comment]
Let me close this for now and reopen when the other PRs are merged.

**Pull request closed without merging**
